DROP TABLE IF EXISTS `ItemType`;

CREATE TABLE `ItemType` (
  `itemTypeId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`itemTypeId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
