DROP TABLE IF EXISTS `Item`;

CREATE TABLE `Item` (
  `itemId` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `itemDetailId` INT UNSIGNED NOT NULL ,
  `storeId` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`itemId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
