DROP TABLE IF EXISTS `Sales`;

CREATE TABLE `Sales` (
  `salesId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `salesTransactionId` INT UNSIGNED NOT NULL ,
  `itemDetailId` INT UNSIGNED NOT NULL,
  `unitPrice` INT UNSIGNED NOT NULL ,
  `qty` INT UNSIGNED NOT NULL,
  `discount` INT UNSIGNED NULL,
  `storeId` INT UNSIGNED NOT NULL ,
  `isVAT` BOOLEAN NOT NULL ,
  PRIMARY KEY (`salesId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
