DROP TABLE IF EXISTS `Store`;

CREATE TABLE `Store` (
  `storeId` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(50) NOT NULL ,
  `location` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`storeId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
