<?php
class Credit_model extends CI_Model
{
	const TBL_NAME = 'Credit';

	public $creditId;
	public $fullName;	// required
	public $address;
	public $phoneNo;
	public $amountPaid;

	public function insert($credit) {
		if (!$credit instanceof Credit_model) {
			throw new Exception("Expected parameter should be an instance of Credit_model.");
		}
		if (empty($credit->fullName)) {
			throw new Exception("Illegal arguments: fullname is required.");
		}
		unset($credit->creditId);	// creditId should be generated by db
		$this->db->insert(self::TBL_NAME, $credit);
		return $this->db->insert_id();
	}
}